# Generated by Django 3.2 on 2021-04-27 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20210427_1248'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
