# Generated by Django 3.2 on 2021-04-27 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApp', '0004_delete_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOwnedTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_shares', models.FloatField(default=0)),
                ('average_cost', models.FloatField(default=0)),
                ('total_return', models.FloatField(default=0)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.team')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
