# Generated by Django 3.2 on 2021-04-27 21:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApp', '0005_userownedteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='share_holders',
            field=models.ManyToManyField(blank=True, related_name='owners', to=settings.AUTH_USER_MODEL),
        ),
    ]
