# Generated by Django 3.2 on 2021-04-28 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_alter_team_share_holders'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='trade_price',
            field=models.FloatField(default=0),
        ),
    ]
