# Generated by Django 3.2 on 2021-04-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_auto_20210428_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='trade_price',
            field=models.FloatField(default=None),
        ),
    ]
