# Generated by Django 3.2 on 2021-04-29 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_alter_transaction_trade_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='num_shares',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trade_price',
            field=models.FloatField(default=0),
        ),
    ]
