# Generated by Django 3.2 on 2021-05-02 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_teamvaluetimestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='trade_value',
            field=models.FloatField(default=0),
        ),
    ]
