# Generated by Django 3.2 on 2021-05-04 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0014_rename_total_return_userownedteam_market_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='userownedteam',
            name='total_return',
            field=models.FloatField(default=0),
        ),
    ]
