# Generated by Django 3.2 on 2021-05-04 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0018_alter_team_background_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='background_image_url',
        ),
        migrations.AddField(
            model_name='team',
            name='bg_image',
            field=models.ImageField(default='None', upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
