# Generated by Django 3.2 on 2021-05-06 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0019_auto_20210504_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='buying_power',
            field=models.FloatField(default=500),
        ),
    ]
