# Generated by Django 3.2 on 2021-05-11 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0020_alter_profile_buying_power'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='full_name',
        ),
    ]
