# Generated by Django 3.2 on 2021-05-13 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0021_rename_name_team_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='conference',
            field=models.CharField(default='West', max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='league_standing',
            field=models.IntegerField(default=0),
        ),
    ]
